# imports

In [2]:
import pandas as pd
from scipy.stats import truncnorm
import numpy as np 
import matplotlib.pyplot as plt 
from scipy.special import expit as activation_function

# reading for the data set

In [3]:
df = pd.read_csv("fashion-mnist_train.csv")
df2 = pd.read_csv("fashion-mnist_test.csv")

# manipulating the data to make it useable

In [4]:
data = np.array(df)
n_samples,n_features = data.shape

data_train = data[0:n_samples].T
Y_train = data_train[0]
X_train = data_train[1:n_features]/255
#data_train.shape

data_test = data[0:n_samples].T
Y_test = data_test[0]
X_test = data_test[1:n_features]/255

# making the neural network class

In [24]:
#relu function
@np.vectorize
def ReLU(x):
    return np.maximum(0,x)

#dderivative of Relu
@np.vectorize
def d_ReLU(x):
    return x > 0

#softmax function
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis = 0)

#sigmoid function
@np.vectorize
def sigmoid(x):
    return 1 / (1 + np.e ** -x)

#derivative of sigmoid
@np.vectorize
def d_sigmoid(x):
    return x * (1.0 - x)

def one_hotY(Y):
    one_hot_Y = np.zeros ( (Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

class neuralNetwork():
    
    def __init__(self, 
                 no_of_in_nodes, 
                 no_of_out_nodes, 
                 no_of_hidden_nodes,
                 learning_rate):
        self.no_of_in_nodes = no_of_in_nodes
        self.no_of_out_nodes = no_of_out_nodes
        self.no_of_hidden_nodes = no_of_hidden_nodes
        self.learning_rate = learning_rate 
        self.create_weight_matrices()
        
    def create_weight_matrices(self):
        self.w1 = np.random.rand(10, 784) - 0.5 
        self.b1 = np.random.rand(10, 1) - 0.5
        self.w2 = np.random.rand(10, 10) - 0.5 
        self.b2 = np.random.rand(10, 1) - 0.5
        return self.w1, self.b1, self.w2, self.b2
    
    def forward_pass(self):
        self.z1 = self.w1.dot(self.no_of_in_nodes) + self.b1
        self.a1 = ReLU(self.z1)
        self.z2 = self.w2.dot(self.a1) + self.b2
        self.a2 = softmax(self.z2)
        return self.a2
        #return self.z1, self.a1, self.z2, self.a2
    
    def backwards_pass(self):
        m = self.no_of_out_nodes.size
        one_hot_Y = one_hotY(self.no_of_out_nodes)
        self.dz2 = self.a2 - one_hot_Y
        self.dw2 = 1/m * self.dz2.dot(self.a1.T)
        self.db2 = 1/m * np.sum(self.dz2)
        self.dz1 = self.w2.T.dot(self.dz2) * d_ReLU(self.z1)
        self.dw1 = 1/m * self.dz1.dot(self.no_of_in_nodes.T)
        self.db1 = 1/m * np.sum(self.dz1)
        #return self.dw1, self.db1, self.dw2, self.db2
    
    def update_params(self):
        self.w1 -= self.learning_rate * self.dw1
        self.b1 -= self.learning_rate * self.db1
        self.w2 -= self.learning_rate * self.dw2
        self.b2 -= self.learning_rate * self.db2
        #return self.w1, self.b1, self.w2, self.b2
        
    def get_predictions(self):
        return np.argmax(self.a2, 0)

    def get_accuracy(self,predictions):
        print(predictions, self.no_of_out_nodes)
        return np.sum(predictions == self.no_of_out_nodes) / self.no_of_out_nodes.size
    
    
    def train(self, epochs):
        self.create_weight_matrices()
        for i in range(epochs):
            self.forward_pass()
            self.backwards_pass()
            self.update_params ()
            print("Iteration: ", i) 
            print("Accuracy: ", self.get_accuracy(self.get_predictions ()))  
            
    def make_predictions(self):
        self.forward_pass()
        predictions = self.get_predictions()
        return predictions
    
    def test_prediction(self, index):
        current_image = X_train[:, index, None]
        prediction = make_predictions()
        label = Y_train[index]
        print("Prediction: ", prediction)
        print("Label: ", label)
        
        current_image = current_image.reshape((28, 28)) * 255
        plt.gray()
        plt.imshow(current_image, interpolation='nearest')
        plt.show()
        
        

In [25]:
model = neuralNetwork(X_train,Y_train, 10 ,0.5)
model.train(10)

Iteration:  0
[7 7 3 ... 0 7 7] [2 9 6 ... 8 8 7]
Accuracy:  0.1041
Iteration:  1
[0 2 0 ... 0 2 0] [2 9 6 ... 8 8 7]
Accuracy:  0.11156666666666666
Iteration:  2
[7 2 2 ... 2 2 7] [2 9 6 ... 8 8 7]
Accuracy:  0.17645
Iteration:  3
[7 7 2 ... 2 2 7] [2 9 6 ... 8 8 7]
Accuracy:  0.17548333333333332
Iteration:  4
[7 7 2 ... 2 2 7] [2 9 6 ... 8 8 7]
Accuracy:  0.20046666666666665
Iteration:  5
[7 7 2 ... 2 2 7] [2 9 6 ... 8 8 7]
Accuracy:  0.2518166666666667
Iteration:  6
[7 7 2 ... 2 2 7] [2 9 6 ... 8 8 7]
Accuracy:  0.27603333333333335
Iteration:  7
[7 7 2 ... 2 2 7] [2 9 6 ... 8 8 7]
Accuracy:  0.285
Iteration:  8
[7 7 2 ... 2 2 7] [2 9 6 ... 8 8 7]
Accuracy:  0.3060833333333333
Iteration:  9
[7 7 2 ... 2 2 7] [2 9 6 ... 8 8 7]
Accuracy:  0.32471666666666665


In [26]:
model.test_prediction(2)

NameError: name 'self' is not defined